### PR TITLE
Fix issues with Combo Box lists

### PR DESCRIPTION
**Pull request by kadet1090**
This fixes issue with ComboBoxes list. I'm not sure what was intended purpose of the fragment that I removed but I did not found any problems.

image

was 

image

### CODE REVIEW

**Comment by obelisk79** [comment]
I am pretty sure I had the min width set for a reason, but I cant remember where I had the problem (addon manager comes to mind). I also prefer having the white space to the left of the list. I'll review the section you removed and see if we can meet in the middle on this.

**Comment by obelisk79** [comment]
Ok, did some testing, and I don't see any issues by removing the code of this pr. Perhaps it was an issue before you changed the preferences window way back when.

**Comment by MisterMakerNL** [comment]
The white space is for an checkmark, default stylesheets have this checkmark, this is because the Fusion pulldown menu doesn't have the selected item on top.
Although it will probably work just fine by removing it, if you feel like it looks better. I am just telling you why it's there.

**Comment by kadet1090** [comment]
If so, the background of item should extend from side to side. Not to say that the mentioned checkmark is not rendered anyway so there is no reason to keep space for it. Uneven padding in that case looks more like an error than intended solution.

**Comment by MisterMakerNL** [comment]
The white space is not the error here it is the missing checkmark :)

**Comment by obelisk79** [comment]
I didn't want the checkmark present. No change in intent here.

**Pull request merged**
